### ISSUE TITLE
Method of Payment

### ISSUE THREAD

**Issue by PinMeister** [PinMeister/COMP-353-Main-Project#19]
- [x] Credit card or chequing account
- [x] Automatic or manual withdrawal
- [ ] If automatic: withdrawal occurs at the beginning of the month
- [x] Can have many methods of payment
- [x] If account is negative (not paid): freeze account until payment is made
- [x] Frozen account can log in but can't do anything
- [ ] Send e-mail informing of charge and account status when charge is applied
- [ ] Suffering account receives warning message once a week until account is settled or deactivated
- [x] Suffering account for a year will be deactivated automatically
